### PR TITLE
Merge changes from Pharo version

### PR DESCRIPTION
**Pull request by jbrichau**
Replaces #2 

We merged-in the changes from the Smalltalkhub version of Pharo, which now resides in https://github.com/pharo-contributions/XML-XMLPullParser

There are no tests inside this project, but the CI setup is ready for it now :-)

### CODE REVIEW

**Comment by dalehenrich** [comment]
could you make a change on your branch to trigger a travis build ... I think that travis missed the recent change because the Github notification api that travis was using stopped functioning :)

**Comment by jbrichau** [comment]
I added GitHub actions for the build and actually removed Travis. Do you want me to include the Travis config as well?

**Comment by dalehenrich** [comment]
Haha, I didn't know that, so I was looking in the wrong place for the test results ... if things look fine for you, go ahead and merge at your leisure ...

**Comment by jbrichau** [comment]
Ha, but indeed, the actions did not run yet in this repo. I guess you need to go and see here: https://github.com/Yesplan/GsXMLPullParser/actions

once they are merged, they should run. I will hit the merge button now and let’s see

**Comment by dalehenrich** [comment]
I see that the actions are running! 

BTW, please feel free to update any other GsDevKit (or other organization) repos to use GitHub actions instead of travis ... I intend to do this when I have a need to directly touch a repo, but the first one will involve a learning curve for me and at the moment I am frying other fish :)

**Pull request merged**
