### PR TITLE
Merge smalltalkhub

### PR DESCRIPTION
**Pull request by akellens**

### CODE REVIEW

**Comment by dalehenrich** [comment]
Cool! @akellens It looks like the .travis.yml is using the ancient builderCI instead of smalltalkCI. Can you create the .smalltalk.ston file and change the .travis.yml to use SmalltalkCI, or do you need me to do that?

**Comment by jbrichau** [comment]
@dalehenrich Hey Dale ;)
Don't worry, we're going to finish this off with pleasure.

(oh and btw, I have not forgotten your emails about the failed Seaside builds. Will check them out soonish!)

**Comment by dalehenrich** [comment]
perfect ... I've got a bunch of balls in the air so I'm not waiting on anything :), instead folks are waiting on me :)

**Comment by akellens** [comment]
@dalehenrich The PR came a bit too soon -- but we'll fix it, as Johan said ;-)

**Comment by dalehenrich** [comment]
No problem, Andy!

**Comment by jbrichau** [comment]
Replaced by #3

**Pull request closed without merging**
